<robot_localization_config>
  <param name="frequency" value="30"/>
  <param name="two_d_mode" value="true"/>

  <param name="map_frame" value="map"/>
  <param name="odom_frame" value="odom"/>
  <param name="base_link_frame" value="base_link"/>

  <param name="imu0" value="/camera/imu"/>
  <param name="imu0_differential" value="false"/>
  <param name="imu0_remove_gravitational_acceleration" value="true"/>
  <param name="imu0_queue_size" value="10"/>
  <param name="imu0_config" value="x y z 0 0 0 0"/>
  <param name="odom0" value="/vins_estimator/odometry"/>
  <param name="odom0_differential" value="true"/>
  <param name="odom0_queue_size" value="10"/>
</robot_localization_config>
